### ISSUE TITLE
License and publishing

### ISSUE THREAD

**Issue by lukoerfer** [SaahilClaypool/DelegateTo#1]
Hi, I found your project searching for this exact thing (basically a source generator that does the same thing as the [Delegate feature of Lombok](https://projectlombok.org/features/experimental/Delegate) for Java), but I noticed that there is no license file in your project, which means that all rights are reserved and noone can actually use your project (see [here](https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license)). If you want to allow others to use your code in any way, you may add a license file for one of the many open source licenses out there.

Additionally, if and when you add a permissive license, it would be really nice to publish your project to Nuget so other can use it directly in their code.

Keep up the good work and best regards!

**Comment by SaahilClaypool** [comment]
Hi @lukoerfer 

Thanks for the comments! I went ahead and added a license & nuget package (although this is largely experimental and untested, it should work well enough for the basic use cases). 

Thanks for the Link to Lombok - I've used that briefly, but hadn't seem their delegate feature.
